spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.matzip: INFO

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 3600000
  refresh-expiration-time: 1209600000 # 14Ïùº

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_PROD_REDIRECT_URI}

app:
  auth:
    allowed-origins:
      - http://localhost:3000
      - https://knu-matzip-dev.vercel.app
      - https://knu-matzip.vercel.app
      - ${ADMIN_ORIGIN:}
    success-path: /login/loading
#    failure-path: /login/loading/fail
    state-secret: ${STATE_SECRET_KEY}
    cookie-secure: false
    cookie-same-site: Lax

image:
  base-url: ${IMAGE_BASE_URL}