spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knu_matzip?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_CLIENT_ID}
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8080/api/v1/auth/callback"
#            scope:
#              - profile_nickname
#              - account_email   # 선택 동의 시
#            client-name: Kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 3600000
  refresh-expiration-time: 1209600000 # 14일

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:8080/api/v1/auth/callback

app:
  auth:
    success-uri: http://localhost:3000/login/success # 임시, 프론트에 확인 필요
    state-secret: ${STATE_SECRET_KEY}
    cookie-secure: false     # 로컬 HTTP 테스트면 false
    cookie-same-site: Lax

image:
  base-url: http://localhost:8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
